In [1]:
import tensorflow as tf

In [2]:
a = [1., 2., 3.] 
# equality_bitcast = tf.bitcast(a, tf.complex128) 

# 这个会报错

In [3]:
equality_cast = tf.cast(a, tf.complex128) 
print(equality_cast) 

tf.Tensor([1.+0.j 2.+0.j 3.+0.j], shape=(3,), dtype=complex128)


In [4]:
tf.bitcast(tf.constant(0xffffffff, dtype=tf.uint32), tf.uint8) 

<tf.Tensor: id=3, shape=(4,), dtype=uint8, numpy=array([255, 255, 255, 255], dtype=uint8)>

In [5]:
x = [1., 2., 3.] 
y = [0., 2., 3.] 
equality = tf.equal(x,y) 
equality_cast = tf.cast(equality,tf.float32) 
equality_bitcast = tf.bitcast(equality_cast,tf.uint8) 
print(equality) 

print(equality_cast) 

print(equality_bitcast) 

tf.Tensor([False  True  True], shape=(3,), dtype=bool)
tf.Tensor([0. 1. 1.], shape=(3,), dtype=float32)
tf.Tensor(
[[  0   0   0   0]
 [  0   0 128  63]
 [  0   0 128  63]], shape=(3, 4), dtype=uint8)


In [6]:
# 没看太明白