In [1]:
import tensorflow as tf

In [2]:
t = tf.constant([[-10., -1., 0.], [0., 2., 10.]]) 
t2 = tf.clip_by_value(t, clip_value_min=-1, clip_value_max=1) 
t2.numpy() 

array([[-1., -1.,  0.],
       [ 0.,  1.,  1.]], dtype=float32)

In [3]:
# 小于下限值，取下限值；大于上限值，取上限值。

In [4]:
s = tf.constant([[-10., -1., 0.5, 0.], [0., 2., -0.5, 10.]]) 
s2 = tf.clip_by_value(s, clip_value_min=-1, clip_value_max=1) 
s2.numpy() 

array([[-1. , -1. ,  0.5,  0. ],
       [ 0. ,  1. , -0.5,  1. ]], dtype=float32)

In [5]:
# 上下限值 可以多维度.

In [7]:
t = tf.constant([[-1, 0., 10.], [-1, 0, 10]]) 
clip_min = [[2],[1]] 
t3 = tf.clip_by_value(t, clip_value_min=clip_min, clip_value_max=100) 
t3.numpy() 

# 做广播

array([[ 2.,  2., 10.],
       [ 1.,  1., 10.]], dtype=float32)

In [9]:
# 如果维度不能广播成功,就会报错