In [1]:
import tensorflow as tf

In [2]:
x = tf.constant([1, 2, 3]) 
y = tf.broadcast_to(x, [3, 3]) 
print(y) 

tf.Tensor(
[[1 2 3]
 [1 2 3]
 [1 2 3]], shape=(3, 3), dtype=int32)


In [3]:
# 这相简单，直接广播就好了。
