In [1]:
import tensorflow as tf

In [2]:
x = [1, 2, 3]

In [3]:
y = [5, 1, 3]

In [4]:
tf.broadcast_dynamic_shape(x, y)

<tf.Tensor: id=2, shape=(3,), dtype=int32, numpy=array([5, 2, 3])>

In [5]:
# 两边互相广播 这里是动态 dynamic，不知道下面的静态static是什么样子的？

In [6]:
x0 = tf.zeros(shape = x)
x0

<tf.Tensor: id=5, shape=(1, 2, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [7]:
y1 = tf.ones(shape = y)
y1

<tf.Tensor: id=8, shape=(5, 1, 3), dtype=float32, numpy=
array([[[1., 1., 1.]],

       [[1., 1., 1.]],

       [[1., 1., 1.]],

       [[1., 1., 1.]],

       [[1., 1., 1.]]], dtype=float32)>

In [8]:
c01 = x0 + y1
c01, c01.shape

(<tf.Tensor: id=9, shape=(5, 2, 3), dtype=float32, numpy=
 array([[[1., 1., 1.],
         [1., 1., 1.]],
 
        [[1., 1., 1.],
         [1., 1., 1.]],
 
        [[1., 1., 1.],
         [1., 1., 1.]],
 
        [[1., 1., 1.],
         [1., 1., 1.]],
 
        [[1., 1., 1.],
         [1., 1., 1.]]], dtype=float32)>, TensorShape([5, 2, 3]))

In [11]:
c2 = tf.broadcast_dynamic_shape(x0.shape, y1.shape)
c2

<tf.Tensor: id=15, shape=(3,), dtype=int32, numpy=array([5, 2, 3])>